import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-insurance-agent-commission-chargeback-reconciliation",
  "engine": "recovery",
  "title": "Insurance Agent Commission & Chargeback Reconciliation",
  "shortTitle": "Insurance Agent Commission and Chargeback Reconciliation",
  "tagline": "Calculate producer commissions and chargebacks across policy lifecycle events, hierarchies, advances, and carrier schedules.",
  "industry": "Insurance Distribution Operations",
  "buyer": "Insurance carriers, MGAs, and agencies",
  "uiPort": 4678,
  "apiPort": 5678,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Insurance Agent Commission & Chargeback Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments in one accountable workflow. Calculate producer commissions and chargebacks across policy lifecycle events, hierarchies, advances, and carrier schedules.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Insurance Agent Commission & Chargeback Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("producer-contract-library","IAC01","Producer contract library","Execute producer contract library using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed producer contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Producer contract library Reference","text","IAC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("license-appointment-validation","IAC02","License appointment validation","Execute license appointment validation using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed license appointment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","License appointment validation Reference","text","IAC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("policy-premium-ingestion","IAC03","Policy premium ingestion","Execute policy premium ingestion using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed policy premium ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Policy premium ingestion Reference","text","IAC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("commission-schedule-mapping","IAC04","Commission schedule mapping","Execute commission schedule mapping using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed commission schedule mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Commission schedule mapping Reference","text","IAC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("hierarchy-split-calculation","IAC05","Hierarchy split calculation","Execute hierarchy split calculation using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed hierarchy split calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Hierarchy split calculation Reference","text","IAC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("new-business-commission","IAC06","New business commission","Execute new business commission using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed new business commission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","New business commission Reference","text","IAC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("renewal-commission","IAC07","Renewal commission","Execute renewal commission using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed renewal commission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Renewal commission Reference","text","IAC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("advance-commission-tracking","IAC08","Advance commission tracking","Execute advance commission tracking using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed advance commission tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Advance commission tracking Reference","text","IAC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("cancellation-chargeback","IAC09","Cancellation chargeback","Execute cancellation chargeback using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed cancellation chargeback decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Cancellation chargeback Reference","text","IAC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("free-look-reversal","IAC10","Free-look reversal","Execute free-look reversal using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed free-look reversal decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Free-look reversal Reference","text","IAC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("replacement-policy-control","IAC11","Replacement policy control","Execute replacement policy control using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed replacement policy control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Replacement policy control Reference","text","IAC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("statement-reconciliation","IAC12","Statement reconciliation","Execute statement reconciliation using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Statement reconciliation Reference","text","IAC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("producer-dispute-workflow","IAC13","Producer dispute workflow","Execute producer dispute workflow using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed producer dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Producer dispute workflow Reference","text","IAC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("cash-payment-reconciliation","IAC14","Cash payment reconciliation","Execute cash payment reconciliation using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed cash payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Cash payment reconciliation Reference","text","IAC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]}),
feature("carrier-producer-analytics","IAC15","Carrier producer analytics","Execute carrier producer analytics using producer contracts, licenses, appointments, policies, premium, commission schedules, advances, cancellations, chargebacks, statements, and payments.","Produce a governed carrier producer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Policy Commission","text","Producer / Policy Commission · Standard Case"],["caseReference","Carrier producer analytics Reference","text","IAC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",988750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1196388],["domainDriver","Commission Event","select","New business",["New business","Renewal","Cancellation"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer contract library case","License appointment validation case","Policy premium ingestion case","Commission schedule mapping case","Hierarchy split calculation case"]})
]);
